export ZSH_CONFIG="$HOME/.config/zsh"

source $ZSH_CONFIG/env.zsh
source $ZSH_CONFIG/aliases.zsh
source $ZSH_CONFIG/functions.zsh
source $ZSH_CONFIG/plugins.zsh
source $ZSH_CONFIG/completion.zsh

eval "$(starship init zsh)"